apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw5-pvc
  namespace: homework
spec:
  accessModes:    
    - ReadWriteOnce
  storageClassName: hw5
  volumeMode: Filesystem  
  resources:    
    requests:      
      storage: 500Mi