apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen 8000;
          server_name localhost;

          location / {
            root /homework;
            index index.html;
          }

          location /conf/file/ {
            alias /homework/conf/;
            autoindex on;
          }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: folder-cm
  namespace: homework
data:
  test.conf: |
    host = 8.8.8.8
    port = 12345 