apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mystorage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mystorage
  namespace: homework
spec:
  accessModes:    
    - ReadWriteOnce
  storageClassName: mystorage
  volumeMode: Filesystem  
  resources:    
    requests:      
      storage: 500Mi