apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8000;
          server_name  homework.otus;
          index  index.html;
          root   /homework;

          location /conf/file/ {
            alias /homework/conf/;
            autoindex on;
          }
      }
    }