apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw4-pvc
  namespace: homework
spec:
  accessModes:    
    - ReadWriteOnce
  storageClassName: hw4
  volumeMode: Filesystem  
  resources:    
    requests:      
      storage: 500Mi