apiVersion: v1
kind: Pod
metadata:
  name: hm1
  namespace: homework
  labels:
    app: hm1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: content
      mountPath: /homework
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "rm /usr/share/nginx/html/index.html && ln -s /homework/index.html /usr/share/nginx/html/index.html"]
      preStop:
        exec:
          command: ["/bin/sh","-c","rm -f /homework/index.html"]
  
  initContainers:
  - name: busybox
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - https://google.com

    volumeMounts:
    - name: content
      mountPath: "/init"
  dnsPolicy: Default
  volumes:
  - name: content
    emptyDir: {}